//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZC_IT_TimeTracking
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Goal_Master> Goal_Master { get; set; }
        public virtual DbSet<Goal_Quater> Goal_Quater { get; set; }
        public virtual DbSet<Goal_Rules> Goal_Rules { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<Resource_Goal> Resource_Goal { get; set; }
        public virtual DbSet<Resource_Goal_Performance> Resource_Goal_Performance { get; set; }
        public virtual DbSet<Resource_Performance> Resource_Performance { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<TeamLead> TeamLeads { get; set; }
    
        public virtual ObjectResult<GetGoalDetails_Result> GetGoalDetails(Nullable<int> goal_Id)
        {
            var goal_IdParameter = goal_Id.HasValue ?
                new ObjectParameter("Goal_Id", goal_Id) :
                new ObjectParameter("Goal_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetGoalDetails_Result>("GetGoalDetails", goal_IdParameter);
        }
    
        public virtual int GetGoalDetails1(Nullable<int> goal_Id)
        {
            var goal_IdParameter = goal_Id.HasValue ?
                new ObjectParameter("Goal_Id", goal_Id) :
                new ObjectParameter("Goal_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetGoalDetails1", goal_IdParameter);
        }
    
        public virtual ObjectResult<GetQuarterDetails_Result> GetQuarterDetails(Nullable<int> quarter_Id)
        {
            var quarter_IdParameter = quarter_Id.HasValue ?
                new ObjectParameter("Quarter_Id", quarter_Id) :
                new ObjectParameter("Quarter_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetQuarterDetails_Result>("GetQuarterDetails", quarter_IdParameter);
        }
    }
}
