//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZC_IT_TimeTracking
{
    using System;
    
    public partial class GetAllGoalsOfResource_Result1
    {
        public int Resource_GoalID { get; set; }
        public string GoalTitle { get; set; }
        public string Name { get; set; }
        public int Weight { get; set; }
    }
}
