//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZC_IT_TimeTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goal_Quater
    {
        public Goal_Quater()
        {
            this.Goal_Master = new HashSet<Goal_Master>();
            this.Resource_Performance = new HashSet<Resource_Performance>();
        }
    
        public int QuaterID { get; set; }
        public int Quater { get; set; }
        public int Year { get; set; }
        public System.DateTime GoalCreateFrom { get; set; }
        public System.DateTime GoalCreateTo { get; set; }
    
        public virtual ICollection<Goal_Master> Goal_Master { get; set; }
        public virtual ICollection<Resource_Performance> Resource_Performance { get; set; }
    }
}
