//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZC_IT_TimeTracking
{
    using System;
    using System.Collections.Generic;
    
    [global::System.CodeDom.Compiler.GeneratedCode("EntityFramework", "4.0.0.0")]
    public partial class Resource_Performance
    {
        public int Resource_PerformanceID { get; set; }
        public int ResourceID { get; set; }
        public int QuaterID { get; set; }
        public double Resource_Performance1 { get; set; }
    
        public virtual Goal_Quarter Goal_Quarter { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
