//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZC_IT_TimeTracking
{
    
    using System;
    using System.Collections.Generic;
    
    [global::System.CodeDom.Compiler.GeneratedCode("EntityFramework", "4.0.0.0")]
    public partial class Resource_Goal_Performance
    
    {
        public int Resource_Goal_PerformanceID { get; set; }
        public double Resource_Performance { get; set; }
        public Nullable<double> Resource_Rating { get; set; }
        public int Resource_GoalId { get; set; }
    
        public virtual Resource_Goal Resource_Goal { get; set; }
    }
}
