USE [master]
GO

/****** Object:  Database [IT-Tracking]    Script Date: 29-10-2015 17:43:25 ******/
CREATE DATABASE [IT-Tracking]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IT-Tracking', FILENAME = N'C:\Users\tpanchal\IT-Tracking.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'IT-Tracking_log', FILENAME = N'C:\Users\tpanchal\IT-Tracking_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [IT-Tracking] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IT-Tracking].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [IT-Tracking] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [IT-Tracking] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [IT-Tracking] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [IT-Tracking] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [IT-Tracking] SET ARITHABORT OFF 
GO

ALTER DATABASE [IT-Tracking] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [IT-Tracking] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [IT-Tracking] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [IT-Tracking] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [IT-Tracking] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [IT-Tracking] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [IT-Tracking] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [IT-Tracking] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [IT-Tracking] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [IT-Tracking] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [IT-Tracking] SET  DISABLE_BROKER 
GO

ALTER DATABASE [IT-Tracking] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [IT-Tracking] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [IT-Tracking] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [IT-Tracking] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [IT-Tracking] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [IT-Tracking] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [IT-Tracking] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [IT-Tracking] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [IT-Tracking] SET  MULTI_USER 
GO

ALTER DATABASE [IT-Tracking] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [IT-Tracking] SET DB_CHAINING OFF 
GO

ALTER DATABASE [IT-Tracking] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [IT-Tracking] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [IT-Tracking] SET  READ_WRITE 
GO

