//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CustomErrorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomErrorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CustomErrorResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error ocurred while Creating Goal!.
        /// </summary>
        internal static string ERR_ADD_GOAL {
            get {
                return ResourceManager.GetString("ERR_ADD_GOAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured while Deleting Goal!.
        /// </summary>
        internal static string ERR_DEL_GOAL {
            get {
                return ResourceManager.GetString("ERR_DEL_GOAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured while Creating Quarter!.
        /// </summary>
        internal static string ERR_DEL_QUA {
            get {
                return ResourceManager.GetString("ERR_DEL_QUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Ocurred while Updating Goal!.
        /// </summary>
        internal static string ERR_EDIT_GOAL {
            get {
                return ResourceManager.GetString("ERR_EDIT_GOAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while Fetching Data!.
        /// </summary>
        internal static string ERR_FETCH_DATA {
            get {
                return ResourceManager.GetString("ERR_FETCH_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured while Fetching Quarter.
        /// </summary>
        internal static string ERR_FETCH_QUA {
            get {
                return ResourceManager.GetString("ERR_FETCH_QUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted goal id not found!.
        /// </summary>
        internal static string ERR_GOAL_ID {
            get {
                return ResourceManager.GetString("ERR_GOAL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Insert Quarter.
        /// </summary>
        internal static string ERR_INS_QUA {
            get {
                return ResourceManager.GetString("ERR_INS_QUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while creating role!.
        /// </summary>
        internal static string ERR_INS_ROLE {
            get {
                return ResourceManager.GetString("ERR_INS_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password!.
        /// </summary>
        internal static string INV_UNM_PSWD {
            get {
                return ResourceManager.GetString("INV_UNM_PSWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested logout failed!.
        /// </summary>
        internal static string LOGOUT_FAIL {
            get {
                return ResourceManager.GetString("LOGOUT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Goal Available!.
        /// </summary>
        internal static string NO_GOAL_AVL {
            get {
                return ResourceManager.GetString("NO_GOAL_AVL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Quarters are available!.
        /// </summary>
        internal static string NO_QUA_AVL {
            get {
                return ResourceManager.GetString("NO_QUA_AVL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records available!.
        /// </summary>
        internal static string NO_REC_AVL {
            get {
                return ResourceManager.GetString("NO_REC_AVL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Rules Define for Goal!.
        /// </summary>
        internal static string NO_RUL_DEF {
            get {
                return ResourceManager.GetString("NO_RUL_DEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Goal Details are not Available!.
        /// </summary>
        internal static string NO_SPF_GOAL_AVL {
            get {
                return ResourceManager.GetString("NO_SPF_GOAL_AVL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This role is already exist!.
        /// </summary>
        internal static string ROLE_EXIST {
            get {
                return ResourceManager.GetString("ROLE_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already exist!.
        /// </summary>
        internal static string USER_EXIST {
            get {
                return ResourceManager.GetString("USER_EXIST", resourceCulture);
            }
        }
    }
}
